### ISSUE TITLE
Move vars/main.yml to defaults

### ISSUE THREAD

**Issue by wezzle** [nsg/ansible-graphite#28]
Hi,

I'm trying to install a different graphite version but when adding the version to `graphite_install_requirements` it get's overridden by the var defined in `vars/main.yml`.

Am I missing a way to add the requirements to that variable or somehow override it with my own variable?

I currently set the following in the group_vars named `graphite`:
```
graphite_install_version: 1.0.2
graphite_install_requirements:
  1.0.2:
    - Django==1.11
    - django-tagging==0.4.3
    - cairocffi==0.8.0
    - pytz==2017.2
    - scandir=1.5
    - python-memcached==1.47
    - txAMQP==0.6.2
    - gunicorn==19.7.0
```

But when running the role with the following inventory:
```
- hosts: graphite
  roles:
    - role: nsg.graphite
```

The variable `graphite_install_requirements` during runtime is (i've added a debug var statement to the role):
```
TASK [nsg.graphite : debug] ****************************************************
ok: [192.168.50.2] => {
    "graphite_install_requirements": {
        "0.9.15": [
            "Django==1.4",
            "python-memcached==1.47",
            "txAMQP==0.4",
            "simplejson==2.1.6",
            "django-tagging==0.3.1",
            "gunicorn==19.6.0",
            "pytz==2016.7",
            "cairocffi==0.7.2",
            "whisper==0.9.13",
            "whitenoise==3.2.2",
            "graphite-web==0.9.15",
            "carbon==0.9.15"
        ]
    }
}
```

Hope you can help me with this

**Comment by nsg** [comment]
Agree, it was a mistake to place these in vars. I assume that #29 fixes all your problems so I will close this issue, if not, feel free to open this issue again. Thank you!
